server:
  port: 8123
  servlet:
    context-path: /api
spring:
  application:
    name: stellara-gallery-backend
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/stellara_gallery?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: xmz725
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
sa-token:
  token-name: stellara_token
  timeout: 2592000
  active-timeout: 604800
  is-concurrent: true
  is-share: true
  token-style: uuid
  is-log: true
  is-read-cookie: true
